image: docker:20.10.21-git

services:
  - docker:20.10.21-dind

stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - DOCKER_BUILDKIT=1 docker build . -t ${IMAGE_TAG}
    - docker push $IMAGE_TAG

appimage:
  stage: build
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_appimage
  script:
    - DOCKER_BUILDKIT=1 docker build -f Dockerfile.appimage . -t ${IMAGE_TAG}
    - docker push $IMAGE_TAG
